/**
 * The in-page agent's model loop. It reads the page's registered tools from the WebMCP surface and
 * executes them through that same surface, so this is another caller of the product's tools rather
 * than a second path to them. A judge whose browser has no WebMCP client gets the tool surface
 * anyway, because the polyfill installs a context when the browser has none.
 */
export type AgentSpeaker = "agent" | "failure" | "person" | "tool";

export interface AgentTurn {
  readonly body?: string;
  readonly id: string;
  readonly label?: string;
  readonly payload?: string;
  readonly speaker: AgentSpeaker;
}

/** One Anthropic message. Content is the provider's own block union, carried but never inspected. */
export interface AgentMessage {
  readonly content: unknown;
  readonly role: "assistant" | "user";
}

interface ToolUseBlock {
  readonly id: string;
  readonly input: unknown;
  readonly name: string;
  readonly type: "tool_use";
}

interface TextBlock {
  readonly text: string;
  readonly type: "text";
}

type ContentBlock = TextBlock | ToolUseBlock | { readonly type: string };

const MAX_TOKENS = 2048;
/** A turn that keeps asking for tools past this has lost the thread; stop rather than loop. */
const MAX_TOOL_ROUNDS = 8;

/**
 * What the model needs before its first call. Without this it meets twenty-one tools and no idea
 * that spans snap to a grid or that captions come from a library, and it spends the visitor's first
 * question discovering both.
 */
const SYSTEM = [
  "You direct a scene of animated actors in this page. Motion is generated by a learned model, so an actor performs a caption rather than playing a clip.",
  "Call read_scene_summary before your first change; it gives the frame count, each actor and its origin and spans, the camera cuts, and the version.",
  "Captions come from the library. Call list_motion_prompts with no arguments to see its facets, then with a filter to get captions. Use a caption exactly as it is written. Only call encode_motion_prompt when the library has nothing close, and if it fails, fall back to the nearest library caption.",
  "Frame ranges snap to a 40-frame grid, so a span starts on a multiple of 40. Say what you changed in one short sentence rather than restating the whole scene.",
  "Camera shots are named the way a director names them: establishing, tracking, follow, close-up, low-angle, crane, reveal, hero. Each is framed off an actor's direction of travel.",
].join(" ");

const isToolUse = (block: ContentBlock): block is ToolUseBlock => block.type === "tool_use";
const isText = (block: ContentBlock): block is TextBlock => block.type === "text";

const readBlocks = (content: unknown): ReadonlyArray<ContentBlock> =>
  Array.isArray(content) ? (content as ReadonlyArray<ContentBlock>) : [];

/** One tool the model asked for, in this file's own shape rather than a provider's. */
interface ToolCall {
  readonly id: string;
  readonly input: unknown;
  readonly name: string;
}

interface OfferedTool {
  readonly description: string | undefined;
  readonly name: string;
  readonly schema: unknown;
}

/** What one answer carried, read out of whichever provider shape it arrived in. */
interface AgentAnswer {
  readonly calls: ReadonlyArray<ToolCall>;
  readonly reply: AgentMessage;
  readonly spoken: string;
}

interface OpenAiToolCall {
  readonly function: { readonly arguments?: string; readonly name: string };
  readonly id: string;
}

const parseArguments = (value: string | undefined): unknown => {
  if (value === undefined || value.trim().length === 0) return {};
  try {
    return JSON.parse(value);
  } catch {
    return {};
  }
};

/**
 * The two providers differ in three places and nowhere else: how tools are offered, how an answer
 * carries its text and its tool calls, and how a tool's result is handed back. Each dialect states
 * those three; the loop below reads them and knows about neither provider.
 */
const DIALECTS = {
  anthropic: {
    model: "claude-sonnet-5",
    read: (answer: Record<string, unknown>): AgentAnswer => {
      const blocks = readBlocks(answer.content);
      return {
        calls: blocks.filter(isToolUse).map(({ id, input, name }) => ({ id, input, name })),
        reply: { content: answer.content, role: "assistant" },
        spoken: blocks
          .filter(isText)
          .map(({ text }) => text)
          .join("\n")
          .trim(),
      };
    },
    request: (messages: ReadonlyArray<AgentMessage>, tools: ReadonlyArray<OfferedTool>) => ({
      max_tokens: MAX_TOKENS,
      messages,
      model: DIALECTS.anthropic.model,
      system: SYSTEM,
      tools: tools.map(({ description, name, schema }) => ({
        description,
        input_schema: schema,
        name,
      })),
    }),
    results: (
      results: ReadonlyArray<{ readonly content: string; readonly id: string }>,
    ): ReadonlyArray<AgentMessage> => [
      {
        content: results.map(({ content, id }) => ({
          content,
          tool_use_id: id,
          type: "tool_result",
        })),
        role: "user",
      },
    ],
  },
  openai: {
    model: "gpt-5.6",
    read: (answer: Record<string, unknown>): AgentAnswer => {
      const choices = Array.isArray(answer.choices) ? answer.choices : [];
      const message = (choices[0] as { readonly message?: Record<string, unknown> } | undefined)
        ?.message;
      const calls = Array.isArray(message?.tool_calls)
        ? (message.tool_calls as ReadonlyArray<OpenAiToolCall>)
        : [];
      return {
        calls: calls.map(({ function: called, id }) => ({
          id,
          input: parseArguments(called.arguments),
          name: called.name,
        })),
        reply: { content: message ?? {}, role: "assistant" },
        spoken: typeof message?.content === "string" ? message.content.trim() : "",
      };
    },
    request: (messages: ReadonlyArray<AgentMessage>, tools: ReadonlyArray<OfferedTool>) => ({
      max_completion_tokens: MAX_TOKENS,
      // This provider carries the whole message as one object, so an assistant turn is its own
      // content and a person's turn is a role with a string. The orientation is a first message
      // here, where the other provider takes it as a field of its own.
      messages: [
        { content: SYSTEM, role: "system" },
        ...messages.map(({ content, role }) =>
          role === "assistant" && typeof content === "object" && content !== null
            ? { role, ...content }
            : { content, role },
        ),
      ],
      model: DIALECTS.openai.model,
      tools: tools.map(({ description, name, schema }) => ({
        function: { description, name, parameters: schema },
        type: "function",
      })),
    }),
    results: (
      results: ReadonlyArray<{ readonly content: string; readonly id: string }>,
    ): ReadonlyArray<AgentMessage> =>
      results.map(({ content, id }) => ({
        content,
        role: "tool" as unknown as "user",
        tool_call_id: id,
      })) as unknown as ReadonlyArray<AgentMessage>,
  },
} as const;

const dialectFor = (provider: string) =>
  provider === "openai" ? DIALECTS.openai : DIALECTS.anthropic;

/**
 * The WebMCP surface carries a tool's input schema as a JSON string, while the model wants the
 * object. A tool whose schema is absent or unreadable still gets offered, taking no arguments,
 * rather than being hidden from the agent.
 */
const EMPTY_SCHEMA = { properties: {}, type: "object" };

const readSchema = (schema: string | undefined): unknown => {
  if (schema === undefined) return EMPTY_SCHEMA;
  try {
    return JSON.parse(schema);
  } catch {
    return EMPTY_SCHEMA;
  }
};

/** The page's tools, in the shape the model expects them. */
const readTools = async () => {
  const context = document.modelContext;
  if (context === undefined) return [];
  const tools = await context.getTools();
  return tools.map((tool) => ({
    description: tool.description,
    input_schema: readSchema(tool.inputSchema),
    name: tool.name,
    tool,
  }));
};

const callModel = async (input: {
  readonly body: unknown;
  readonly key: string;
  readonly provider: string;
}) => {
  const response = await fetch("/api/agent", {
    body: JSON.stringify(input.body),
    headers: {
      "content-type": "application/json",
      "x-agent-key": input.key,
      "x-agent-provider": input.provider,
    },
    method: "POST",
  });
  const text = await response.text();
  if (!response.ok) throw new Error(text.slice(0, 400));
  return JSON.parse(text) as { readonly content?: unknown; readonly stop_reason?: string };
};

/**
 * Run one exchange to completion: the model answers, and while it asks for tools they are executed
 * on the page and handed back. Every tool call is reported as it happens, so the transcript shows
 * what the agent did to the scene and not only what it said.
 */
export const runAgentExchange = async (input: {
  readonly history: ReadonlyArray<AgentMessage>;
  readonly key: string;
  readonly onTurn: (turn: AgentTurn) => void;
  readonly prompt: string;
  readonly provider: string;
}): Promise<ReadonlyArray<AgentMessage>> => {
  const available = await readTools();
  const dialect = dialectFor(input.provider);
  const tools = available.map(({ description, input_schema, name }) => ({
    description,
    name,
    schema: input_schema,
  }));

  const advance = async (
    messages: ReadonlyArray<AgentMessage>,
    round: number,
  ): Promise<ReadonlyArray<AgentMessage>> => {
    const answer = await callModel({
      body: dialect.request(messages, tools),
      key: input.key,
      provider: input.provider,
    });
    const { calls: requested, reply, spoken } = dialect.read(answer as Record<string, unknown>);
    if (spoken.length > 0) {
      input.onTurn({ body: spoken, id: crypto.randomUUID(), speaker: "agent" });
    }
    const withAnswer = [...messages, reply];
    if (requested.length === 0) return withAnswer;
    if (round >= MAX_TOOL_ROUNDS) {
      input.onTurn({
        body: `The agent asked for tools ${String(MAX_TOOL_ROUNDS)} times without finishing; the exchange stopped here.`,
        id: crypto.randomUUID(),
        speaker: "failure",
      });
      return withAnswer;
    }

    const results = await Promise.all(
      requested.map(async (block) => {
        const known = available.find(({ name }) => name === block.name);
        if (known === undefined) {
          return { content: `"${block.name}" is not registered on this page.`, id: block.id };
        }
        // executeTool takes its arguments as a JSON string, not an object.
        const outcome = await document
          .modelContext!.executeTool(known.tool, JSON.stringify(block.input ?? {}))
          .then(
            (value) => value ?? "",
            (cause: unknown) => (cause instanceof Error ? cause.message : String(cause)),
          );
        input.onTurn({
          id: crypto.randomUUID(),
          label: block.name,
          payload: `${JSON.stringify(block.input ?? {}, undefined, 2)}\n→ ${outcome}`,
          speaker: "tool",
        });
        return { content: outcome, id: block.id };
      }),
    );

    return advance([...withAnswer, ...dialect.results(results)], round + 1);
  };

  return advance([...input.history, { content: input.prompt, role: "user" }], 0);
};
