/**
 * The in-page agent's model loop. It reads the page's registered tools from the WebMCP surface and
 * executes them through that same surface, so this is another caller of the product's tools rather
 * than a second path to them. A judge whose browser has no WebMCP client gets the tool surface
 * anyway, because the polyfill installs a context when the browser has none.
 */
import { PUBLISHED_FRAMES_PER_WINDOW } from "webgpu-engine/motion";

import { CAMERA_SHOT_PRESETS } from "../../scene/cinematography";

export type AgentSpeaker = "agent" | "failure" | "person" | "tool";

export interface AgentTurn {
  readonly body?: string;
  readonly id: string;
  /** A data URL, when the tool returned an image. Shown to the person, never sent to the model. */
  readonly image?: string;
  readonly label?: string;
  readonly payload?: string;
  readonly speaker: AgentSpeaker;
}

/** One Anthropic message. Content is the provider's own block union, carried but never inspected. */
export interface AgentMessage {
  readonly content: unknown;
  readonly role: "assistant" | "user";
}

interface ToolUseBlock {
  readonly id: string;
  readonly input: unknown;
  readonly name: string;
  readonly type: "tool_use";
}

interface TextBlock {
  readonly text: string;
  readonly type: "text";
}

type ContentBlock = TextBlock | ToolUseBlock | { readonly type: string };

const MAX_TOKENS = 2048;
/** A turn that keeps asking for tools past this has lost the thread; stop rather than loop. */
const MAX_TOOL_ROUNDS = 8;
/**
 * How much conversation is carried into the next question. Every tool result stays in the history,
 * and a read tool answers with most of the composition, so an unbounded history reaches the
 * provider's context limit after a handful of questions and every later one fails outright.
 * Forgetting the older questions keeps the panel usable, which a hard refusal does not.
 */
const HISTORY_LIMIT = 120_000;

/**
 * What the model needs before its first call. Without this it meets twenty-one tools and no idea
 * that spans snap to a grid or that captions come from a library, and it spends the visitor's first
 * question discovering both.
 */
const SYSTEM = [
  "You direct a scene of animated actors in this page. Motion is generated by a learned model, so an actor performs a caption rather than playing a clip.",
  "Start with read_scene_readiness. Stop if its status is failed. Once open, call read_scene_summary before the first change.",
  "A browser without WebGPU and shader-f16 never opens the scene, so only the readiness tool is registered there. If a tool you expect is missing, report what readiness said about this browser instead of guessing.",
  "Never overwrite an existing scene for a new request. Use author_scene to create a complete new scene with its initial cast, motion, coverage, and environment in one operation. Use create_scene only when the user wants to build progressively from an empty scene. Use list_scenes and open_scene to revisit saved work.",
  "Build or revise with add_actor, set_environment_entity, remove_environment_entity, set_scene_look, set_motion_span, and set_camera_timeline_item. Call control_motion_scene restart after the cast and shots are ready, then capture the result.",
  "Call list_environment_assets before set_environment. Environment entries are entities with asset, transform, and color components; compose them as one coherent place rather than unrelated props.",
  "Captions come from the library. Search list_motion_prompts with query for each intended action; use category, posture, tag, or pace filters only when broader exploration helps. Never load the full catalog unless the user explicitly asks for it. Use a returned caption exactly as written. Call encode_motion_prompt only when search finds nothing close.",
  `Frame ranges snap to a ${String(PUBLISHED_FRAMES_PER_WINDOW)}-frame grid, so a span starts on a multiple of ${String(PUBLISHED_FRAMES_PER_WINDOW)}. Use read_scene_summary for routine decisions; read the full composition only when an exact item identity is unavailable elsewhere. Say what you changed in one short sentence rather than restating the whole scene.`,
  `Camera shots are named the way a director names them: ${CAMERA_SHOT_PRESETS.join(", ")}. Each is framed off an actor's direction of travel.`,
  "A character is a .glb this site serves. inspect_character says whether it carries every joint the model drives; wear_character dresses the scene's actors in it. Wearing a character, like newScene, reopens the scene: the tools unregister for a moment and read_scene_readiness reports open again when they return, which is not a browser limitation.",
].join(" ");

const isToolUse = (block: ContentBlock): block is ToolUseBlock => block.type === "tool_use";
const isText = (block: ContentBlock): block is TextBlock => block.type === "text";

const readBlocks = (content: unknown): ReadonlyArray<ContentBlock> =>
  Array.isArray(content) ? (content as ReadonlyArray<ContentBlock>) : [];

/**
 * How much of one tool's result is handed back. The read tools answer with the whole composition
 * when asked, and every result stays in the history for the rest of the exchange, so an unbounded
 * one ends the conversation a few turns later. The agent is told where the cut fell and which tool
 * answers the same question in summary.
 */
const RESULT_LIMIT = 6000;

const boundResult = (outcome: string) =>
  outcome.length <= RESULT_LIMIT
    ? outcome
    : `${outcome.slice(0, RESULT_LIMIT)}\n\n[cut after ${String(RESULT_LIMIT)} of ${String(outcome.length)} characters. read_scene_summary answers the same question compactly.]`;

/**
 * A result arrives as JSON of the whole tool result, so an image block carries its base64 inside
 * that string — megabytes of it for a contact sheet. Bounding it would hand the model thousands of
 * characters it cannot read and cut away the receipt that follows. The image goes to the person and
 * the receipt goes to the model, which is the split each of them can actually use.
 */
const capturedImage = (raw: string) => {
  if (!raw.startsWith("{")) return undefined;
  try {
    const result = JSON.parse(raw) as {
      readonly content?: ReadonlyArray<{
        readonly data?: string;
        readonly mimeType?: string;
        readonly type?: string;
      }>;
      readonly structuredContent?: unknown;
    };
    const image = result.content?.find((block) => block.type === "image");
    if (image?.data === undefined) return undefined;
    return {
      receipt: JSON.stringify(result.structuredContent ?? {}),
      source: `data:${image.mimeType ?? "image/png"};base64,${image.data}`,
    };
  } catch {
    return undefined;
  }
};

/** One tool the model asked for, in this file's own shape rather than a provider's. */
interface ToolCall {
  readonly id: string;
  readonly input: unknown;
  readonly name: string;
}

interface OfferedTool {
  readonly description: string | undefined;
  readonly name: string;
  readonly schema: unknown;
}

/** What one answer carried, read out of whichever provider shape it arrived in. */
interface AgentAnswer {
  readonly calls: ReadonlyArray<ToolCall>;
  readonly reply: AgentMessage;
  readonly spoken: string;
}

interface OpenAiToolCall {
  readonly function: { readonly arguments?: string; readonly name: string };
  readonly id: string;
}

const parseArguments = (value: string | undefined): unknown => {
  if (value === undefined || value.trim().length === 0) return {};
  try {
    return JSON.parse(value);
  } catch {
    return {};
  }
};

/**
 * The two providers differ in three places and nowhere else: how tools are offered, how an answer
 * carries its text and its tool calls, and how a tool's result is handed back. Each dialect states
 * those three; the loop below reads them and knows about neither provider.
 */
const DIALECTS = {
  anthropic: {
    model: "claude-sonnet-5",
    read: (answer: Record<string, unknown>): AgentAnswer => {
      const blocks = readBlocks(answer.content);
      return {
        calls: blocks.filter(isToolUse).map(({ id, input, name }) => ({ id, input, name })),
        reply: { content: answer.content, role: "assistant" },
        spoken: blocks
          .filter(isText)
          .map(({ text }) => text)
          .join("\n")
          .trim(),
      };
    },
    request: (messages: ReadonlyArray<AgentMessage>, tools: ReadonlyArray<OfferedTool>) => ({
      max_tokens: MAX_TOKENS,
      messages,
      model: DIALECTS.anthropic.model,
      system: SYSTEM,
      tools: tools.map(({ description, name, schema }) => ({
        description,
        input_schema: schema,
        name,
      })),
    }),
    results: (
      results: ReadonlyArray<{ readonly content: string; readonly id: string }>,
    ): ReadonlyArray<AgentMessage> => [
      {
        content: results.map(({ content, id }) => ({
          content,
          tool_use_id: id,
          type: "tool_result",
        })),
        role: "user",
      },
    ],
  },
  openai: {
    model: "gpt-5.6",
    read: (answer: Record<string, unknown>): AgentAnswer => {
      const choices = Array.isArray(answer.choices) ? answer.choices : [];
      const message = (choices[0] as { readonly message?: Record<string, unknown> } | undefined)
        ?.message;
      const calls = Array.isArray(message?.tool_calls)
        ? (message.tool_calls as ReadonlyArray<OpenAiToolCall>)
        : [];
      return {
        calls: calls.map(({ function: called, id }) => ({
          id,
          input: parseArguments(called.arguments),
          name: called.name,
        })),
        reply: { content: message ?? {}, role: "assistant" },
        spoken: typeof message?.content === "string" ? message.content.trim() : "",
      };
    },
    request: (messages: ReadonlyArray<AgentMessage>, tools: ReadonlyArray<OfferedTool>) => ({
      max_completion_tokens: MAX_TOKENS,
      // This provider carries the whole message as one object, so an assistant turn is its own
      // content and a person's turn is a role with a string. The orientation is a first message
      // here, where the other provider takes it as a field of its own.
      messages: [
        { content: SYSTEM, role: "system" },
        ...messages.map(({ content, role }) =>
          role === "assistant" && typeof content === "object" && content !== null
            ? { role, ...content }
            : { content, role },
        ),
      ],
      model: DIALECTS.openai.model,
      tools: tools.map(({ description, name, schema }) => ({
        function: { description, name, parameters: schema },
        type: "function",
      })),
    }),
    results: (
      results: ReadonlyArray<{ readonly content: string; readonly id: string }>,
    ): ReadonlyArray<AgentMessage> =>
      results.map(({ content, id }) => ({
        content,
        role: "tool" as unknown as "user",
        tool_call_id: id,
      })) as unknown as ReadonlyArray<AgentMessage>,
  },
} as const;

const dialectFor = (provider: string) =>
  provider === "openai" ? DIALECTS.openai : DIALECTS.anthropic;

/**
 * The WebMCP surface carries a tool's input schema as a JSON string, while the model wants the
 * object. A tool whose schema is absent or unreadable still gets offered, taking no arguments,
 * rather than being hidden from the agent.
 */
const EMPTY_SCHEMA = { properties: {}, type: "object" };

const readSchema = (schema: string | undefined): unknown => {
  if (schema === undefined) return EMPTY_SCHEMA;
  try {
    return JSON.parse(schema);
  } catch {
    return EMPTY_SCHEMA;
  }
};

/**
 * The page's tools. The polyfill is imported here as well as by the registration, because a
 * visitor can send a message while the scene is still opening, and a module import is cached: this
 * awaits the same promise rather than doing the work twice. An empty surface is reported instead of
 * being answered around, since an agent with no tools gives a confident useless answer.
 */
const readTools = async () => {
  if (document.modelContext === undefined) await import("@mcp-b/global");
  const context = document.modelContext;
  if (context === undefined) {
    throw new Error(
      "This browser exposes no WebMCP surface, so the page's tools cannot be called.",
    );
  }
  const tools = await context.getTools();
  if (tools.length === 0) {
    throw new Error(
      "The page's tools are not registered yet. Wait for the scene to open, then ask again.",
    );
  }
  return tools.map((tool) => ({
    description: tool.description,
    input_schema: readSchema(tool.inputSchema),
    name: tool.name,
    tool,
  }));
};

/** Both providers report a failure as `{ error: { message } }`; the route's own refusals are text. */
const providerFailure = (text: string): string => {
  try {
    const parsed = JSON.parse(text) as { readonly error?: { readonly message?: unknown } };
    const message = parsed.error?.message;
    return typeof message === "string" && message.length > 0 ? message : text.slice(0, 400);
  } catch {
    return text.slice(0, 400);
  }
};

const callModel = async (input: {
  readonly body: unknown;
  readonly key: string;
  readonly provider: string;
}) => {
  const response = await fetch("/api/agent", {
    body: JSON.stringify(input.body),
    headers: {
      "content-type": "application/json",
      "x-agent-key": input.key,
      "x-agent-provider": input.provider,
    },
    method: "POST",
  });
  const text = await response.text();
  if (!response.ok) throw new Error(providerFailure(text));
  return JSON.parse(text) as { readonly content?: unknown; readonly stop_reason?: string };
};

/**
 * Run one exchange to completion: the model answers, and while it asks for tools they are executed
 * on the page and handed back. Every tool call is reported as it happens, so the transcript shows
 * what the agent did to the scene and not only what it said.
 */
export const runAgentExchange = async (input: {
  readonly history: ReadonlyArray<AgentMessage>;
  readonly key: string;
  readonly onTurn: (turn: AgentTurn) => void;
  readonly prompt: string;
  readonly provider: string;
}): Promise<ReadonlyArray<AgentMessage>> => {
  const available = await readTools();
  const dialect = dialectFor(input.provider);
  const tools = available.map(({ description, input_schema, name }) => ({
    description,
    name,
    schema: input_schema,
  }));

  const advance = async (
    messages: ReadonlyArray<AgentMessage>,
    round: number,
  ): Promise<ReadonlyArray<AgentMessage>> => {
    const answer = await callModel({
      body: dialect.request(messages, tools),
      key: input.key,
      provider: input.provider,
    });
    const { calls: requested, reply, spoken } = dialect.read(answer as Record<string, unknown>);
    if (spoken.length > 0) {
      input.onTurn({ body: spoken, id: crypto.randomUUID(), speaker: "agent" });
    }
    const withAnswer = [...messages, reply];
    if (requested.length === 0) return withAnswer;
    if (round >= MAX_TOOL_ROUNDS) {
      input.onTurn({
        body: `The agent asked for tools ${String(MAX_TOOL_ROUNDS)} times without finishing; the exchange stopped here.`,
        id: crypto.randomUUID(),
        speaker: "failure",
      });
      // Drop the unanswered reply: both providers refuse a tool call with no result after it.
      return messages;
    }

    // These tools mutate one composition and each re-reads it, so parallel calls edit a stale read.
    const results = await requested.reduce<
      Promise<ReadonlyArray<{ readonly content: string; readonly id: string }>>
    >(async (earlier, block) => {
      const done = await earlier;
      const known = available.find(({ name }) => name === block.name);
      if (known === undefined) {
        return [
          ...done,
          { content: `"${block.name}" is not registered on this page.`, id: block.id },
        ];
      }
      // executeTool takes its arguments as a JSON string, not an object.
      const raw = await document
        .modelContext!.executeTool(known.tool, JSON.stringify(block.input ?? {}))
        .then(
          (value) => value ?? "",
          (cause: unknown) => (cause instanceof Error ? cause.message : String(cause)),
        );
      // Read the image before bounding: a cut string is no longer the JSON that carries it.
      const captured = capturedImage(raw);
      const outcome =
        captured === undefined
          ? boundResult(raw)
          : `${captured.receipt}\n\n[the image is displayed to the person]`;
      input.onTurn({
        id: crypto.randomUUID(),
        ...(captured === undefined ? {} : { image: captured.source }),
        label: block.name,
        payload: `${JSON.stringify(block.input ?? {}, undefined, 2)}\n→ ${outcome}`,
        speaker: "tool",
      });
      return [...done, { content: outcome, id: block.id }];
    }, Promise.resolve([]));

    return advance([...withAnswer, ...dialect.results(results)], round + 1);
  };

  const complete = await advance([...input.history, { content: input.prompt, role: "user" }], 0);
  // The only cut that is always safe: this exchange alone, which opens on the person's own message
  // and answers every tool call it made. Cutting anywhere inside one strands a call without result.
  return JSON.stringify(complete).length <= HISTORY_LIMIT
    ? complete
    : complete.slice(input.history.length);
};
