/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMotionGifRouteImport } from './routes/api.motion-gif'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as ApiMotionModelArtifactRouteImport } from './routes/api.motion-model.$artifact'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMotionGifRoute = ApiMotionGifRouteImport.update({
  id: '/api/motion-gif',
  path: '/api/motion-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMotionModelArtifactRoute = ApiMotionModelArtifactRouteImport.update({
  id: '/api/motion-model/$artifact',
  path: '/api/motion-model/$artifact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/motion-gif': typeof ApiMotionGifRoute
  '/api/motion-model/$artifact': typeof ApiMotionModelArtifactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/motion-gif': typeof ApiMotionGifRoute
  '/api/motion-model/$artifact': typeof ApiMotionModelArtifactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/motion-gif': typeof ApiMotionGifRoute
  '/api/motion-model/$artifact': typeof ApiMotionModelArtifactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/api/agent'
    | '/api/motion-gif'
    | '/api/motion-model/$artifact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/api/agent'
    | '/api/motion-gif'
    | '/api/motion-model/$artifact'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/api/agent'
    | '/api/motion-gif'
    | '/api/motion-model/$artifact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiMotionGifRoute: typeof ApiMotionGifRoute
  ApiMotionModelArtifactRoute: typeof ApiMotionModelArtifactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/motion-gif': {
      id: '/api/motion-gif'
      path: '/api/motion-gif'
      fullPath: '/api/motion-gif'
      preLoaderRoute: typeof ApiMotionGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/motion-model/$artifact': {
      id: '/api/motion-model/$artifact'
      path: '/api/motion-model/$artifact'
      fullPath: '/api/motion-model/$artifact'
      preLoaderRoute: typeof ApiMotionModelArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiMotionGifRoute: ApiMotionGifRoute,
  ApiMotionModelArtifactRoute: ApiMotionModelArtifactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
